"""user.info_text

Revision ID: 028d3ac7278e
Revises: 566ec65280e8
Create Date: 2016-06-03 18:47:40.407858

"""

# revision identifiers, used by Alembic.
revision = '028d3ac7278e'
down_revision = '566ec65280e8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('info_text', sa.Text(), nullable=False, server_default=''))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('info_text')
    ### end Alembic commands ###
