"""challenge model

Revision ID: 187feb1b9af0
Revises: b51fd5a5242c
Create Date: 2016-05-21 10:26:02.007113

"""

# revision identifiers, used by Alembic.
revision = '187feb1b9af0'
down_revision = 'b51fd5a5242c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgres import ENUM


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('challengee_id', sa.Integer(), nullable=False),
    sa.Column('board_size', sa.Integer(), nullable=False),
    sa.Column('komi', sa.Float(), nullable=False),
    sa.Column('handicap', sa.Integer(), nullable=False),
    sa.Column('owner_is_black', sa.Boolean(), nullable=False),
    sa.Column('timing_system', ENUM('fischer', 'byoyomi', name='timing_system', create_type=False), nullable=False),
    sa.Column('maintime', sa.Interval(), nullable=False),
    sa.Column('overtime', sa.Interval(), nullable=False),
    sa.Column('overtime_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('owner_id != challengee_id'),
    sa.ForeignKeyConstraint(['challengee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'challengee_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenges')
    ### end Alembic commands ###
