"""timings

Revision ID: 7692b9c0472b
Revises: 8b2198695679
Create Date: 2016-05-08 13:46:34.416138

"""

# revision identifiers, used by Alembic.
revision = '7692b9c0472b'
down_revision = '8b2198695679'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('timing_updated_at', sa.DateTime(), nullable=True),
    sa.Column('next_move_at', sa.DateTime(), nullable=True),
    sa.Column('system', sa.Enum('fischer', 'byoyomi', name='timing_system'), nullable=False),
    sa.Column('main', sa.Interval(), nullable=False),
    sa.Column('overtime', sa.Interval(), nullable=False),
    sa.Column('overtime_count', sa.Integer(), nullable=False),
    sa.Column('black_main', sa.Interval(), nullable=False),
    sa.Column('black_overtime', sa.Interval(), nullable=False),
    sa.Column('white_main', sa.Interval(), nullable=False),
    sa.Column('white_overtime', sa.Interval(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timings')
    ### end Alembic commands ###
