"""games

Revision ID: 889c4f6a8ef8
Revises: 0c819768171a
Create Date: 2016-05-01 19:51:26.309636

"""

# revision identifiers, used by Alembic.
revision = '889c4f6a8ef8'
down_revision = '0c819768171a'

from alembic import op
import sqlalchemy as sa
import weiqi.models


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('is_ranked', sa.Boolean(), nullable=False),
    sa.Column('stage', sa.Enum('playing', 'counting', 'finished', name='game_stage'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('board', weiqi.models.BoardData(), nullable=False),
    sa.Column('komi', sa.Float(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('result_black_confirmed', sa.String(), nullable=False),
    sa.Column('result_white_confirmed', sa.String(), nullable=False),
    sa.Column('black_user_id', sa.Integer(), nullable=True),
    sa.Column('white_user_id', sa.Integer(), nullable=True),
    sa.Column('black_display', sa.String(), nullable=False),
    sa.Column('white_display', sa.String(), nullable=False),
    sa.Column('black_rating', sa.Float(), nullable=True),
    sa.Column('white_rating', sa.Float(), nullable=True),
    sa.Column('demo_owner_id', sa.Integer(), nullable=True),
    sa.Column('demo_owner_rating', sa.Float(), nullable=True),
    sa.Column('demo_control_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('NOT is_ranked OR NOT is_demo', name='demo_ranked_check'),
    sa.ForeignKeyConstraint(['black_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['demo_control_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['demo_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['white_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('automatch', sa.Column('user_rating', sa.Float(), nullable=False, server_default=sa.false()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automatch', 'user_rating')
    op.drop_table('games')
    ### end Alembic commands ###
