"""users.last_activity_at

Revision ID: 8b2198695679
Revises: 12ba6b1cba2d
Create Date: 2016-05-07 22:09:20.118438

"""

# revision identifiers, used by Alembic.
revision = '8b2198695679'
down_revision = '12ba6b1cba2d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity_at')
    ### end Alembic commands ###
