"""last_rating_update_at

Revision ID: b0be0cca1485
Revises: 11af601ae470
Create Date: 2016-05-06 12:25:55.839793

"""

# revision identifiers, used by Alembic.
revision = 'b0be0cca1485'
down_revision = '11af601ae470'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_rating_update_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_rating_update_at')
    ### end Alembic commands ###
