"""rooms.users_max

Revision ID: b51fd5a5242c
Revises: f4aaa313bfa0
Create Date: 2016-05-15 11:03:01.605735

"""

# revision identifiers, used by Alembic.
revision = 'b51fd5a5242c'
down_revision = 'f4aaa313bfa0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('users_max', sa.Integer(), nullable=False, server_default='0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'users_max')
    ### end Alembic commands ###
