"""ranked challenges

Revision ID: baadf574c940
Revises: e43b33a75e6f
Create Date: 2016-07-02 09:41:01.907829

"""

# revision identifiers, used by Alembic.
revision = 'baadf574c940'
down_revision = 'e43b33a75e6f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenges', sa.Column('is_ranked', sa.Boolean(), nullable=False, server_default=sa.false()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenges', 'is_ranked')
    ### end Alembic commands ###
