"""users.is_active

Revision ID: f4aaa313bfa0
Revises: 7692b9c0472b
Create Date: 2016-05-10 19:08:18.286581

"""

# revision identifiers, used by Alembic.
revision = 'f4aaa313bfa0'
down_revision = '7692b9c0472b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    ### end Alembic commands ###
